### ISSUE TITLE
 kubectl apply -f config/samples/ doesnt work

### ISSUE THREAD

**Issue by outbackdingo** [guilhem/headscale-operator#2]
kubectl apply -f config/samples/
resource mapping not found for name: "namespace-sample" namespace: "" from "config/samples/headscale_v1alpha1_namespace.yaml": no matches for kind "Namespace" in version "headscale.barpilot.io/v1alpha1"
ensure CRDs are installed first
resource mapping not found for name: "preauthkey-sample" namespace: "" from "config/samples/headscale_v1alpha1_preauthkey.yaml": no matches for kind "PreAuthKey" in version "headscale.barpilot.io/v1alpha1"
ensure CRDs are installed first
resource mapping not found for name: "server-sample" namespace: "" from "config/samples/headscale_v1alpha1_server.yaml": no matches for kind "Server" in version "headscale.barpilot.io/v1alpha1"
ensure CRDs are installed first

**Comment by guilhem** [comment]
Indeed, `kubectl apply -f config/samples/` should be done after a `make install` which put CRD in K8S cluster.

**Comment by guilhem** [comment]
I have to update doc :)

**Comment by outbackdingo** [comment]
yeah well it kinda creates a further issue for us, we dont use docker, wount go near it, we use podman, all your work is very docker specific and relies on a working access to a viable cluster also..... feels like alot of hoops just to deploy this.

**Comment by tuarrep** [comment]
You can also simply run `kubectl apply -f config/crd/bases/`
